export * from "./basicDate.zSchema";
export * from "./basicIcon.zSchema";
export * from "./basicLocation.zSchema";
export * from "./biodata.zSchema";
export * from "./education.zSchema";
export * from "./experience.zSchema";
export * from "./skill.zSchema";
export * from "./basicHighlights.zSchema";
export * from "./image.zSchema";